version: '3.8'

services:
  gateway:
    env_file: .env
    build: ./gateway
    ports:
      - "8083:8083"  # !!!Only gateway exposes ports to outside
    depends_on:
      - userservice
      - authservice
      - orderservice
      - paymentservice
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVICES_USERSERVICE_URL=http://userservice:8080
      - SERVICES_AUTHSERVICE_URL=http://authservice:8081
      - SERVICES_ORDERSERVICE_URL=http://orderservice:8082
      - SERVICES_PAYMENTSERVICE_URL=http://paymentservice:8084
      - SERVER_PORT=8083
    networks:
      - myproject-network

  userservice:
    env_file: .env
    build: ./userservice
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      - SPRING_LIQUIBASE_USER=${DB_USER}
      - SPRING_LIQUIBASE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
    networks:
      - myproject-network

  authservice:
    env_file: .env
    build: ./authservice
    expose:
      - "8081"
    depends_on: #
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_AUTH_NAME}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_AUTH_NAME}?sslmode=disable
      - SPRING_LIQUIBASE_USER=${DB_USER}
      - SPRING_LIQUIBASE_PASSWORD=${DB_PASSWORD}
    networks:
      - myproject-network
    
  orderservice:
    env_file: .env
    build: ./orderservice
    expose:
      - "8082"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_ORDER_NAME}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_ORDER_NAME}?sslmode=disable
      - SPRING_LIQUIBASE_USER=${DB_USER}
      - SPRING_LIQUIBASE_PASSWORD=${DB_PASSWORD}
    networks:
      - myproject-network

  paymentservice:
    build: ./paymentservice
    container_name: paymentservice
    expose:
      - "8084"
    env_file:
      - .env
    depends_on:
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/paymentDB
    command: [ "java", "-jar", "app.jar" ]
    networks:
      - myproject-network

  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: userserviceDB  # Creates a DB on startup
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Saves data to "volume"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf  # Enable custom pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Check command
      interval: 5s # Checking every 5 seconds
      timeout: 5s # Checking timeout
      retries: 5 # Number of attempts
    networks:
      - myproject-network

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning # command without password
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # without password
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - myproject-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")' || exit 1" ]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 30s
    networks:
      - myproject-network

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s
    networks:
      - myproject-network

volumes:
  postgres-data:
  mongo_data:

networks: # added a network to make all services to be in the same network and the DNS error went away (userservice cannot find the redis service)
  myproject-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16