name: CI Pipeline for Spring Boot JAR (Gateway)

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Clone the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create JWT public key
      - name: Create JWT public key
        run: |
          mkdir -p src/main/resources/keys
          echo "${{ secrets.PUBLIC_KEY }}" > src/main/resources/keys/public.pem
          echo "âœ… Public key created"

      # 3. Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      # 4. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 5. Build and test with Maven
      - name: Build and test with Maven
        run: |
          mvn clean package -DskipTests

      # 6. SonarCloud Scan
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=juliakaiko_gateway \
            -Dsonar.organization=juliakaiko \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -DskipTests

      # 7. Docker Build and Push
      - name: Docker Build and Push
        if: success() && github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.TOKEN_FOR_GATEWAY }}
        run: |
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t juliakaiko94/gateway:latest .
          docker push juliakaiko94/gateway:latest